/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-03-12 15:29:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Hệ Thống Quản Lý Xưởng Mộc Hoàng Hoan</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	background: #ecf0f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("	width: 250px;\r\n");
      out.write("	background: #34495e;\r\n");
      out.write("	color: white;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	box-shadow: 3px 0 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar h2 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	border-bottom: 2px solid #1abc9c;\r\n");
      out.write("	padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar ul li {\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	transition: background 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar ul li a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: background 0.3s, transform 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar ul li a:hover {\r\n");
      out.write("	background: #1abc9c;\r\n");
      out.write("	transform: translateX(5px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("	flex-grow: 1;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content h1 {\r\n");
      out.write("	color: #2c3e50;\r\n");
      out.write("	font-size: 28px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-container {\r\n");
      out.write("	display: grid;\r\n");
      out.write("	grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("	gap: 20px;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card {\r\n");
      out.write("	background: white;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("	transition: transform 0.3s ease;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card:hover {\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	max-width: 200px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card h3 {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	color: #2c3e50;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card p {\r\n");
      out.write("	color: #1abc9c;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card button {\r\n");
      out.write("	background: #1abc9c;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 8px 12px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: background 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card button:hover {\r\n");
      out.write("	background: #16a085;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("		<h2>Menu</h2>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"viewform\">Sản Phẩm</a></li>\r\n");
      out.write("			<li><a href=\"thietbi/list\">Thiết Bị</a></li>\r\n");
      out.write("			<li><a href=\"giohang\">Giỏ Hàng</a></li>\r\n");
      out.write("			<li><a href=\"admin/list\">Quản Trị</a></li>\r\n");
      out.write("\r\n");
      out.write("			<li><a href=\"admin/login\">Đăng Nhập</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<h1>Bàn Gỗ</h1>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"product-container\">\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<a href=\"#\"> <img\r\n");
      out.write("					src=\"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSveplbTzJ7eMzgfmn9Wq5gt5yYDCRy4fJiavzYrEbD85ljuw_WUVlcFUxqz6vdK32ygq5m0S1i_BpImftEq2JkMN6ztNSQgKccx4C9f1FnwnBEWa-2ieZG1w&usqp=CAE\"\r\n");
      out.write("					alt=\"Laptop Dell\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<h3>Bàn gỗ tự nhiên thiết ké đa năng SD256</h3>\r\n");
      out.write("				<p>Giá: 5,000,000 VNĐ</p>\r\n");
      out.write("				<p>Số lượng: 100</p>\r\n");
      out.write("				<button onclick=\"window.location.href='viewform'\">Xem thêm</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<a href=\"#\"> <img\r\n");
      out.write("					src=\"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSM2Dwl58mkp6Zwu_HYQ8mmd6z8VFRnfeE24VANMuVXQ4BmWefHV7i93xqAG9Vq6BFV0yatK2t2OM4YIVibneRbe6bgezi1HA&usqp=CAE\"\r\n");
      out.write("					alt=\"iPhone 14\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<h3>Bàn trà nhật gỗ xoan</h3>\r\n");
      out.write("				<p>Giá: 2,000,000 VNĐ</p>\r\n");
      out.write("				<p>Số lượng: 56</p>\r\n");
      out.write("				<button onclick=\"window.location.href='viewform'\">Xem thêm</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<a href=\"#\"> <img\r\n");
      out.write("					src=\"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTfbIMR9sUbnJjj4DuRqhO6n-MJYRkKlMRF_Ou86w5PGQ04VHkZdRIV1YY4sXyokoLQYBkbxeq-8o6mA8Jx7CAiuZCG47gG4TfGbjlOwRVQ&usqp=CAE\"\r\n");
      out.write("					alt=\"Samsung Galaxy\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<h3>Bàn gỗ tự nhiên kết hợp tủ lưu trữ đa năng TG061</h3>\r\n");
      out.write("				<p>Giá: 2,100,000 VNĐ</p>\r\n");
      out.write("				<p>Số lượng: 81</p>\r\n");
      out.write("				<button onclick=\"window.location.href='viewform'\">Xem thêm</button>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<a href=\"#\"> <img\r\n");
      out.write("					src=\"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRw-G-00iAoAbxlGrUVMkFUWsuLjx6m7PakMq8imePqJW4ib6HrHdDJZXOnoIIkZTGrIjTCcsl-CgStm1muiDVXDUt8DrvV6lRQj5sU9096&usqp=CAE\"\r\n");
      out.write("					alt=\"Tai nghe Sony\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<h3>Bàn Gỗ Tự Nhiên Bàn Làm việc kèm giá sách di động đa năng\r\n");
      out.write("					OpenLiving OBG 043</h3>\r\n");
      out.write("				<p>Giá: 13,000,000 VNĐ</p>\r\n");
      out.write("				<p>Số lượng: 220</p>\r\n");
      out.write("				<button onclick=\"window.location.href='viewform'\">Xem thêm</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<h1>Tủ Gỗ</h1>\r\n");
      out.write("		<div class=\"product-container\">\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<a href=\"#\"> <img\r\n");
      out.write("					src=\"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQPeizyS_OgohWriGEhmd8E1iNUfVKxYaLhsoIFQy6vQ6G1KTSFlPvXYmBtcIR6zLFZfP28yQiOwYJrpNd59vl9FT4qbeNcsaaMDyKrog&usqp=CAE\"\r\n");
      out.write("					alt=\"Laptop Dell\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<h3>Tủ quần áo nhôm vân gỗ</h3>\r\n");
      out.write("				<p>Giá: 51,000,000 VNĐ</p>\r\n");
      out.write("				<p>Số lượng: 10</p>\r\n");
      out.write("				<button onclick=\"window.location.href='viewform'\">Xem thêm</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<a href=\"#\"> <img\r\n");
      out.write("					src=\"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQrmSHnu62bUY_jtg9HKzeHXXV8u-Bb5czw_zuBj2U4c6Wq0j1bUm_y1fPagmmMgaryLCcUxecy4059DSC-U2-WV63AzKPYET6dXSdy0kfj&usqp=CAE\"\r\n");
      out.write("					alt=\"iPhone 14\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<h3>Tủ quần áo gỗ kết hợp, thiết kế tiện nghi BR118</h3>\r\n");
      out.write("				<p>Giá: 42,000,000 VNĐ</p>\r\n");
      out.write("				<p>Số lượng: 56</p>\r\n");
      out.write("				<button onclick=\"window.location.href='viewform'\">Xem thêm</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
