/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-03-10 13:02:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Hệ Thống Quản Lý Nhân Viên</title>\r\n");
      out.write("    <style>\r\n");
      out.write("       body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            background: #ecf0f1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            background: #34495e;\r\n");
      out.write("            color: white;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            box-shadow: 3px 0 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border-bottom: 2px solid #1abc9c;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar ul {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar ul li {\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar ul li a {\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: background 0.3s, transform 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar ul li a:hover {\r\n");
      out.write("            background: #1abc9c;\r\n");
      out.write("            transform: translateX(5px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content h1 {\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-container {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-card img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 200px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-card h3 {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-card p {\r\n");
      out.write("            color: #1abc9c;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-card button {\r\n");
      out.write("            background: #1abc9c;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-card button:hover {\r\n");
      out.write("            background: #16a085;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <h2>Menu</h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#\">Danh sách</a></li>\r\n");
      out.write("            <li><a href=\"#\">Lịch Sử Dùng</a></li>\r\n");
      out.write("            <li><a href=\"#\">Người Dùng</a></li>\r\n");
      out.write("            <li><a href=\"#\">Trang TB</a></li>\r\n");
      out.write("            <li><a href=\"admin/list\">Quản Trị</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <h1>Danh mục sản phẩm</h1>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"product-container\">\r\n");
      out.write("            <div class=\"product-card\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/200\" alt=\"Laptop Dell\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <h3>Laptop Dell</h3>\r\n");
      out.write("                <p>Giá: 15,000,000 VNĐ</p>\r\n");
      out.write("                <p>Số lượng: 10</p>\r\n");
      out.write("                <button>Xem thêm</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"product-card\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/200\" alt=\"iPhone 14\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <h3>iPhone 14</h3>\r\n");
      out.write("                <p>Giá: 25,000,000 VNĐ</p>\r\n");
      out.write("                <p>Số lượng: 5</p>\r\n");
      out.write("                <button>Xem thêm</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"product-card\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/200\" alt=\"Samsung Galaxy\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <h3>Samsung Galaxy</h3>\r\n");
      out.write("                <p>Giá: 20,000,000 VNĐ</p>\r\n");
      out.write("                <p>Số lượng: 8</p>\r\n");
      out.write("                <button>Xem thêm</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"product-card\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/200\" alt=\"Tai nghe Sony\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <h3>Tai nghe Sony</h3>\r\n");
      out.write("                <p>Giá: 3,000,000 VNĐ</p>\r\n");
      out.write("                <p>Số lượng: 20</p>\r\n");
      out.write("                <button>Xem thêm</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"product-card\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/200\" alt=\"Tai nghe Sony\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <h3>Tai nghe Sony</h3>\r\n");
      out.write("                <p>Giá: 3,000,000 VNĐ</p>\r\n");
      out.write("                <p>Số lượng: 20</p>\r\n");
      out.write("                <button>Xem thêm</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
